version: "3"
services:
  datasphere-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile-Prod
    image: datasphere-backend:prod
    env_file:
      - ./.secret.env
    user: "1000001"
  revproxy:
    build: 
      context: ./caddy
      dockerfile: Dockerfile-Prod
    image: revproxy:prod
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - caddy_data:/data
    depends_on:
      - datasphere-backend

volumes:
  caddy_data:
