version: "3"
services:
  datasphere-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile-Dev
    volumes:
      - ./backend:/opt/app
    image: datasphere-backend:dev
    user: "1000001"
  revproxy:
    build: 
      context: ./caddy
      dockerfile: Dockerfile-Dev
    ports:
      - "443:443"
      - "80:80"
      - "4000:4000"
    volumes:
      - ./frontend:/usr/share/caddy
      - caddy_data:/data
    depends_on:
      - datasphere-backend

volumes:
  caddy_data:
